name: build

on: push

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [18, 20, 21, 22]
        os: ["bullseye", "alpine"]
    env:
      default_node: 22
      default_os: bullseye
      pnpm_patch: "9.15.2"
      pnpm_minor: "9.15"
      pnpm_major: "9"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            base=${{ matrix.node }}-${{ matrix.os }}
            pnpm=${{ env.pnpm_patch }}
          tags: |
            gplane/pnpm:${{ env.pnpm_patch }}-node${{ matrix.node }}-${{ matrix.os }}
            gplane/pnpm:${{ env.pnpm_minor }}-node${{ matrix.node }}-${{ matrix.os }}
            gplane/pnpm:${{ env.pnpm_major }}-node${{ matrix.node }}-${{ matrix.os }}
            gplane/pnpm:node${{ matrix.node }}-${{ matrix.os }}
          push: true
      - name: Build images with default OS
        if: ${{ matrix.os == env.default_os }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            base=${{ matrix.node }}-${{ env.default_os }}
            pnpm=${{ env.pnpm_patch }}
          tags: |
            gplane/pnpm:${{ env.pnpm_patch }}-node${{ matrix.node }}
            gplane/pnpm:${{ env.pnpm_minor }}-node${{ matrix.node }}
            gplane/pnpm:${{ env.pnpm_major }}-node${{ matrix.node }}
            gplane/pnpm:node${{ matrix.node }}
          push: true
      - name: Build images with default Node.js
        if: ${{ matrix.node == env.default_node }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            base=${{ env.default_node }}-${{ matrix.os }}
            pnpm=${{ env.pnpm_patch }}
          tags: |
            gplane/pnpm:${{ env.pnpm_patch }}-${{ matrix.os }}
            gplane/pnpm:${{ env.pnpm_minor }}-${{ matrix.os }}
            gplane/pnpm:${{ env.pnpm_major }}-${{ matrix.os }}
            gplane/pnpm:${{ matrix.os }}
          push: true
      - name: Build images with default Node.js and default OS
        if: ${{ matrix.node == env.default_node && matrix.os == env.default_os }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            base=${{ env.default_node }}-${{ env.default_os }}
            pnpm=${{ env.pnpm_patch }}
          tags: |
            gplane/pnpm:${{ env.pnpm_patch }}
            gplane/pnpm:${{ env.pnpm_minor }}
            gplane/pnpm:${{ env.pnpm_major }}
            gplane/pnpm
          push: true
